on:
  push:
    branches:
      - master
name: Production Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://103.253.212.228
          ftp-username: devalkhair@dev.alkhair.or.id
          ftp-password: ${{ secrets.FTP_PASSWORD }}
